# Generated by Django 3.1.1 on 2024-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_auto_20240522_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.IntegerField(default=True),
        ),
    ]
