# Generated by Django 3.1.1 on 2024-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_post_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visited',
        ),
        migrations.AddField(
            model_name='post',
            name='num_site',
            field=models.IntegerField(default=0, verbose_name='visited'),
        ),
    ]
